---
- name: guacamole
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  tasks:

    - name: Set container_command = podman for rhel9
      set_fact:
        container_command: podman
      when:
        - ansible_os_family == 'RedHat' and ansible_distribution_major_version == "9"
    
    - name: Determine if (One Time) was done
      stat:
        path: /opt/guacamole/one_time_done
      register: guacdb_one_time_done
    
    - name: Nginx data dir
      file:
        path: /opt/nginx/ssl
        state: directory
        owner: root
        group: root
        mode: '0750'
 
    - name: Nginx config files
      copy:
        src: nginx/
        dest: /opt/nginx/
    
    - name: Configure Nginx SSL cert (One Time)
      shell: 
        # credentials
        "openssl req -nodes -newkey rsa:2048 -new -x509 -keyout /opt/nginx/ssl/self-ssl.key -out /opt/nginx/ssl/self.cert -subj '/C=RU/ST=St.Petersburg/L=St.Petersburg/O=UNIX Education Center/OU=Training/CN=foundation0.ilt.example.com/emailAddress=instructor@ilt.example.com'"
      when: guacdb_one_time_done.stat.exists|bool == False

    - name: Guacamole data dir
      file:
        path: /opt/guacamole
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Guacamole branding data dir
      file:
        path: /opt/guacamole/extensions
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Guacamole branding file
      copy:
        src: branding.jar
        dest: /opt/guacamole/extensions/branding.jar

    - name: Determine db passwords set (root)
      stat:
        path: /opt/guacamole/guacdb_root_file
      register: guacdb_root_file

    - name: Determine db passwords set (guacamole)
      stat:
        path: /opt/guacamole/guacdb_guacamole_file
      register: guacdb_guacamole_file

    - name: Create db passwords when not set (root)
      shell: |
        head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 > /opt/guacamole/guacdb_root_file
      when: guacdb_root_file.stat.exists|bool == False

    - name: Create db passwords when not set (guacamole)
      shell: |
        head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 > /opt/guacamole/guacdb_guacamole_file
      when: guacdb_guacamole_file.stat.exists|bool == False

    - name: Register db passwords
      shell: |
        cat /opt/guacamole/guacdb_root_file
      register: guacdb_root_pass

    - name: Register db pass (guacamole)
      shell: |
        cat /opt/guacamole/guacdb_guacamole_file
      register: guacdb_guacamole_pass


    - name: Docker Volume (db)
      shell: |
        {{ container_command }} volume create guacdb
      when: guacdb_one_time_done.stat.exists|bool == False
      ignore_errors: true
      
    - name: Container Launch - podman
      shell: |
        {{ container_command }} run -d --name guacd --ip {{ guacnet_guacd }} docker.io/guacamole/guacd-dev
        {{ container_command }} run -d --name guacdb --ip {{ guacnet_guacdb }} --volume guacdb:/var/lib/mysql:Z -e MYSQL_ROOT_PASSWORD={{ guacdb_root_pass.stdout }} docker.io/mysql/mysql-server
        {{ container_command }} run -d --name guacamole --ip {{ guacnet_guacamole }} -e MYSQL_HOSTNAME={{ guacnet_guacdb }} -e MYSQL_PORT=3306 -e MYSQL_DATABASE=guacamole_db -e MYSQL_USERNAME=guacamole_user -e MYSQL_PASSWORD={{ guacdb_guacamole_pass.stdout }} -e GUACD_HOSTNAME={{ guacnet_guacd }} -e GUACD_PORT=4822 -e GUACD_LOG_LEVEL=debug -v /opt/guacamole:/etc/guacamole:Z  docker.io/guacamole/guacamole-dev
        {{ container_command }} run -d  --name nginx --ip {{ guacnet_nginx }} -p 8443:8443 -v /opt/nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:Z -v /opt/nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:Z -v /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:Z -v /opt/nginx/mysite.template:/etc/nginx/conf.d/default.conf:Z  docker.io/library/nginx
      when:
        - container_command == 'podman'


    - name: Set my.cnf and dbpass.sql
      template:
        src: "{{ item }}"
        dest: "/opt/guacamole/{{ item }}"
        owner: root
        group: root
        mode: '0400'
      with_items:
        - my.cnf
        - dbpass.sql
      when: guacdb_one_time_done.stat.exists|bool == False

    - name: Wait for mysqld on 3306
      shell: |
        {{ container_command }} logs guacdb 2>&1 | grep --quiet 'port: 3306'
      register: wait_for_mysqld
      until: wait_for_mysqld.rc == 0
      retries: 15
      delay: 15
      when: guacdb_one_time_done.stat.exists|bool == False

    - name: Configure DB (One Time)
      shell: |
        # credentials
        {{ container_command }} cp /opt/guacamole/my.cnf guacdb:/root/.my.cnf
        {{ container_command }} cp /opt/guacamole/dbpass.sql guacdb:dbpass.sql
        {{ container_command }} exec -i guacdb /bin/bash -c "mysql < dbpass.sql"
        touch /opt/guacamole/one_time_done
        # schema
        {{ container_command }} exec -i guacamole /bin/bash -c 'cat /opt/guacamole/mysql/schema/*.sql' > /opt/guacamole/dbschema.sql
        {{ container_command }} cp /opt/guacamole/dbschema.sql guacdb:dbschema.sql
        {{ container_command }} exec -i guacdb /bin/bash -c "mysql guacamole_db < dbschema.sql"
      when: guacdb_one_time_done.stat.exists|bool == False
