---
- name: guacamole
  hosts: "{{ target }}"
  gather_facts: true
  become: true
  tasks:

    - name: Set container_command = podman for rhel8
      set_fact:
        container_command: podman
      when:
        - ansible_os_family == 'RedHat' and ansible_distribution_major_version == "9"

    - name: Container Stop - podman
      shell: |
        {{ container_command }} stop guacd 
        {{ container_command }} stop guacdb 
        {{ container_command }} stop guacamole 
        {{ container_command }} stop nginx 

    - name: Container Remove - podman
      shell: |
        {{ container_command }} rm guacd 
        {{ container_command }} rm guacdb 
        {{ container_command }} rm guacamole 
        {{ container_command }} rm nginx 


