---
- name: guacamole
  hosts: "{{ target }}"
  gather_facts: true
  tasks:

    - name: Set container_command = podman for rhel8
      set_fact:
        container_command: podman
      when:
        - ansible_os_family == 'RedHat' and ansible_distribution_major_version == "8"
    - name: Guacamole db dir
      file:
        path: /var/local/guacdb/data
        state: directory
        mode: '0777'

    - name: Determine db passwords set (root)
      stat:
        path: /var/local/guacdb/guacdb_root_file
      register: guacdb_root_file

    - name: Determine db passwords set (guacamole)
      stat:
        path: /var/local/guacdb/guacdb_guacamole_file
      register: guacdb_guacamole_file

    - name: Create db passwords when not set (root)
      shell: |
        head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 > /var/local/guacdb/guacdb_root_file
      when: guacdb_root_file.stat.exists|bool == False

    - name: Create db passwords when not set (guacamole)
      shell: |
        head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 > /var/local/guacdb/guacdb_guacamole_file
      when: guacdb_guacamole_file.stat.exists|bool == False

    - name: Register db passwords
      shell: |
        cat /var/local/guacdb/guacdb_root_file
      register: guacdb_root_pass

    - name: Register db pass (guacamole)
      shell: |
        cat /var/local/guacdb/guacdb_guacamole_file
      register: guacdb_guacamole_pass

    - name: Container Launch - podman
      shell: |
              {{ container_command }} pod create --name guac  -p 3306:3306 -p 8443:8443 -p 8080:8080
      when:
        - container_command == 'podman'
    
    - name: Container Launch - podman
      shell: |
        {{ container_command }} run -d --name guacdb --pod guac --volume /var/local/guacdb/data:/var/lib/mysql:Z -e MYSQL_ROOT_PASSWORD={{ guacdb_root_pass.stdout }} docker.io/mysql/mysql-server
      when:
        - container_command == 'podman'

    - name: Set my.cnf and dbpass.sql
      template:
        src: "{{ item }}"
        dest: "/var/local/guacdb/{{ item }}"
        mode: '0666'
      with_items:
        - my.cnf
        - dbpass.sql

    - name: Wait for mysqld on 3306
      shell: |
        {{ container_command }} logs guacdb 2>&1 | grep --quiet 'port: 3306'
      register: wait_for_mysqld
      until: wait_for_mysqld.rc == 0
      retries: 15
      delay: 15

    - name: Guacamole branding data dir
      file:
        path: /var/local/guac/extensions
        state: directory
        mode: '0777'
    - name: Guacamole branding file
      copy:
        src: branding.jar
        dest: /var/local/guac/extensions/branding.jar
      
    - name: Container Launch - podman
      shell: |
        {{ container_command }} run -d --name guacd --pod guac docker.io/guacamole/guacd
        {{ container_command }} run -d --name guacamole --pod guac -e MYSQL_HOSTNAME=localhost -e MYSQL_PORT=3306 -e MYSQL_DATABASE=guacamole_db -e MYSQL_USER=guacamole_user -e MYSQL_PASSWORD={{ guacdb_guacamole_pass.stdout }} -e GUACD_HOSTNAME=localhost -e GUACD_PORT=4822 -e GUACD_LOG_LEVEL=debug -e GUACAMOLE_HOME=/opt/guac -v /var/local/guac:/opt/guac:Z  docker.io/guacamole/guacamole
